### ISSUE TITLE
OutOfMemoryExeption

### ISSUE THREAD

**Issue by nicolasguzca** [zoranmax/ZORAN.DB.IP.Importer#1]
Hi! I am currently using the ip dataset of May 2018 and I'm getting an OutOfMemoryExeption error.

![screen shot 2018-05-09 at 12 56 08 pm](https://user-images.githubusercontent.com/5486518/39830960-8c287af6-5388-11e8-90f3-29ba172f5f20.png)

Any workarounds to fix this? maybe cut the csv in two parts?

**Comment by zoranmax** [comment]
Hi Nicolas,

This code has been written a while ago and it was not really optimized as it loads all the data from the file in memory (RAM).

I could reproduce the issue you have, and it looks like the limit is the limit of the 32 bit process to which the version 1.0.0 is compiled against.

I've done some changes to the code so that:
- Now the solution is converted to x64.
- Solution uses the newest CsvHelper library.
- Migration to .NET 4.5.2

After this, you will see a bigger usage of RAM on your system (due to the x64 switch), but now the app will be able to fully use the memory.

Can you please try it out and let me know?
You may download the v1.1.0 of the application linked in the ReadMe file.

**Comment by nicolasguzca** [comment]
Hi Zoran! 
Thank you, will test it out tomorrow. Thank you for all your help!
